using System.Text;
using SpongeEngine.SubtitleSharp.Utils;

namespace SpongeEngine.SubtitleSharp.Writers
{
    /// <summary>
    /// Implements writing of subtitle items to an SSA (SubStation Alpha) file.
    /// 
    /// The output SSA file includes a header and an [Events] section with dialogue entries.
    /// </summary>
    public class SsaWriter : ISubtitleWriter
    {
        /// <summary>
        /// Writes the SSA file header to the specified <see cref="TextWriter"/>.
        /// </summary>
        /// <param name="writer">The <see cref="TextWriter"/> to write to.</param>
        /// <param name="wrapStyle">The wrap style to specify for the file (defaults to <see cref="SsaWrapStyle.None"/>).</param>
        private void WriteHeader(TextWriter writer, SsaWrapStyle wrapStyle = SsaWrapStyle.None)
        {
            writer.WriteLine(SsaFormatConstants.SCRIPT_INFO_LINE);
            writer.WriteLine($"{SsaFormatConstants.COMMENT} Script generated by SubtitlesParser v{GetType().Assembly.GetName().Version}");
            writer.WriteLine($"{SsaFormatConstants.COMMENT} https://github.com/AlexPoint/SubtitlesParser");
            writer.WriteLine("ScriptType: v4.00");
            writer.WriteLine($"{SsaFormatConstants.WRAP_STYLE_PREFIX}{wrapStyle}");
            writer.WriteLine(); // Blank line between sections

            writer.Flush();
        }

        /// <summary>
        /// Asynchronously writes the SSA file header to the specified <see cref="TextWriter"/>.
        /// </summary>
        /// <param name="writer">The <see cref="TextWriter"/> to write to.</param>
        /// <param name="wrapStyle">The wrap style to specify for the file (defaults to <see cref="SsaWrapStyle.None"/>).</param>
        private async Task WriteHeaderAsync(TextWriter writer, SsaWrapStyle wrapStyle = SsaWrapStyle.None)
        {
            await writer.WriteLineAsync(SsaFormatConstants.SCRIPT_INFO_LINE);
            await writer.WriteLineAsync($"{SsaFormatConstants.COMMENT} Script generated by SubtitlesParser v{GetType().Assembly.GetName().Version}");
            await writer.WriteLineAsync($"{SsaFormatConstants.COMMENT} https://github.com/AlexPoint/SubtitlesParser");
            await writer.WriteLineAsync("ScriptType: v4.00");
            await writer.WriteLineAsync($"{SsaFormatConstants.WRAP_STYLE_PREFIX}{wrapStyle}");
            await writer.WriteLineAsync(); // Blank line between sections

            await writer.FlushAsync();
        }

        /// <summary>
        /// Converts a <see cref="SubtitleItem"/> into an SSA-formatted dialogue line.
        /// </summary>
        /// <param name="subtitleItem">The subtitle item to convert.</param>
        /// <param name="includeFormatting">
        /// Determines whether to include formatting codes. If <c>false</c> and <see cref="SubtitleItem.PlaintextLines"/> is set,
        /// those lines will be used instead.
        /// </param>
        /// <returns>A formatted dialogue line as a string.</returns>
        private string SubtitleItemToDialogueLine(SubtitleItem subtitleItem, bool includeFormatting)
        {
            string[] fields = new string[10]; // Fields for layer, start, end, style, name, margins, effect, and text.
            fields[0] = "0"; // Layer (default 0)
            fields[1] = TimeSpan.FromMilliseconds(subtitleItem.StartTime).ToString(@"h\:mm\:ss\.fff"); // Start time
            fields[2] = TimeSpan.FromMilliseconds(subtitleItem.EndTime).ToString(@"h\:mm\:ss\.fff");   // End time
            fields[5] = "0"; // Left margin
            fields[6] = "0"; // Right margin 
            fields[7] = "0"; // Vertical margin

            // Combine text lines, using either the formatted or plaintext version.
            List<string> lines = includeFormatting == false && subtitleItem.PlaintextLines != null ?
                subtitleItem.PlaintextLines :
                subtitleItem.Lines;
            fields[9] = lines.Aggregate(string.Empty, (current, line) => current + $"{line}\\N").TrimEnd('\\', 'N');

            StringBuilder builder = new StringBuilder(SsaFormatConstants.DIALOGUE_PREFIX);
            return builder.AppendJoin(SsaFormatConstants.SEPARATOR, fields).ToString();
        }

        /// <summary>
        /// Writes a collection of subtitle items to a stream in SSA format synchronously.
        /// </summary>
        /// <param name="stream">The output stream.</param>
        /// <param name="subtitleItems">The subtitle items to write.</param>
        /// <param name="includeFormatting">
        /// Determines whether to include formatting codes. If <c>false</c>, <see cref="SubtitleItem.PlaintextLines"/> should be populated.
        /// </param>
        public void WriteStream(Stream stream, IEnumerable<SubtitleItem> subtitleItems, bool includeFormatting = true)
        {
            using TextWriter writer = new StreamWriter(stream);
            WriteHeader(writer);

            writer.WriteLine(SsaFormatConstants.EVENT_LINE);
            writer.WriteLine("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"); // Column headers
            foreach (SubtitleItem item in subtitleItems)
                writer.WriteLine(SubtitleItemToDialogueLine(item, includeFormatting));
        }

        /// <summary>
        /// Writes a collection of subtitle items to a stream in SSA format asynchronously.
        /// </summary>
        /// <param name="stream">The output stream.</param>
        /// <param name="subtitleItems">The subtitle items to write.</param>
        /// <param name="includeFormatting">
        /// Determines whether to include formatting codes. If <c>false</c>, <see cref="SubtitleItem.PlaintextLines"/> should be populated.
        /// </param>
        /// <returns>A task representing the asynchronous write operation.</returns>
        public async Task WriteStreamAsync(Stream stream, IEnumerable<SubtitleItem> subtitleItems, bool includeFormatting = true)
        {
            await using TextWriter writer = new StreamWriter(stream);
            await WriteHeaderAsync(writer);

            await writer.WriteLineAsync(SsaFormatConstants.EVENT_LINE);
            await writer.WriteLineAsync("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"); // Column headers
            foreach (SubtitleItem item in subtitleItems)
                await writer.WriteLineAsync(SubtitleItemToDialogueLine(item, includeFormatting));
        }
    }
}